braincilonaction/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('dudupage.urls'), name="dudupage"),
    path('account/', include(('account.urls'), 'account'), name="account"),
    path('loginpage/', include(('loginpage.urls'), 'loginpage'), name="loginpage"),
    path('qna/', include(('qna.urls'), 'qna'), name="qna"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
    path('question/', views.question, name='question'),
    path('hasil/<int:id_det>/', views.hasil, name='hasil'),
]

qna/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Pertanyaan(models.Model):
    usernanya = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    matpel = models.CharField(default=0, max_length=100, choices = [
            ('Matematika', 'Matematika'),
            ('Fisika', 'Fisika'),
            ('Kimia', 'Kimia'),
            ('Biologi', 'Biologi'),
            ('IPS', 'IPS'),
            ('PKN', 'PKN'),
            ('Indonesia', 'Indonesia'), 
            ('Inggris', 'Inggris'),
            ('IT', 'IT'),
        ],)
    waktu = models.DateTimeField(default=timezone.now)
    pertanyaan = models.CharField(max_length=255)

    def __str__(self):
        return self.pertanyaan
    

class Jawaban(models.Model):
    userjawab = models.ForeignKey(User, on_delete=models.CASCADE, default=0)
    pertanyaan = models.ForeignKey(Pertanyaan, on_delete=models.CASCADE, default=0)
    waktu = models.DateTimeField(default=timezone.now)
    jawaban = models.CharField(max_length=255)
        
    def __str__(self):
        return self.jawaban

qna/forms.py
from django import forms
from qna.models import Jawaban, Pertanyaan

class JawabanForm(forms.Form):
    error_messages = {
        'required' : 'Please Type',
    }

    jawaban_attrs = {
        'placeholder' : 'Mau jawab...',
        'class' : 'form-control',
        'required' : True,
    }

    jawaban = forms.CharField(label="Jawaban", widget=forms.TextInput(attrs=jawaban_attrs))
    

qna/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pertanyaan, Jawaban
from .forms import JawabanForm
from django.contrib.auth.decorators import login_required

response={}
@login_required
def question(request):
    form = JawabanForm(request.POST)
    if request.method=='POST' :
        jawabans = request.POST.get("jawaban")
        pertanyaans = request.POST.get("p_id")
        question = Pertanyaan.objects.get(id=pertanyaans)
        Jawaban(userjawab=request.user, jawaban=jawabans, pertanyaan=question).save()
        return redirect('/qna/hasil/'+ str(pertanyaans))
    form = JawabanForm()
    response['form'] = form
    pertanyaan = Pertanyaan.objects.all()
    response['pertanyaan'] = pertanyaan
    return render (request, 'qna/question.html', response)

@login_required
def hasil(request, id_det):
    jawaban = Jawaban.objects.filter(pertanyaan__id=id_det)
    response['jawaban'] = jawaban
    return render (request, 'qna/hasil.html', response)

qna/templates/qna/hasil.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'static/css/style.css' %}"> -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    {%block style%}
    <link rel="stylesheet" href="{% static 'qna/css/question.css' %}">
    {%endblock style%}
    <title> Register </title>
</head>


<body>
    {%block content%}
    <section id="navbarMatkul">
      <div class="navMatkulCurhat col">
        <div class="navMatkul row">
          <a href="#">
            <h3 class="tulisanMatkul"> Matematika </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Fisika </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Kimia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Kimia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Biologi </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> IPS </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> PKN </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Indonesia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Inggris </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> IT </h3>
          </a>
        </div>
      </section>
      <section id="curhatAkademik">
        <div class="curhat row">
          <button class="btn btn-primary intabel" method="POST">Curhatan Siswa</button>
        </div>
      </section> 

      <section id="cardQuestion">
        <div class="container">
          <div class="col">
            {%if jawaban%}
                {%for j in jawaban%}
                  <div class="col-sm-6">
                    <div class="card">
                      <div class="card-body">
                        <div class="cardTitle row">
                          <img id="fotoakun2" src="{{j.userjawab.profile.image.url}}" class="rounded-circle">
                          <div class="tulisanjudul row">
                            <h5 id="cardtitle" class="card-title">{{j.userjawab.first_name}} {{j.userjawab.last_name}}</h5>
                            <h5 id="cardtitle" class="card-title"> {{j.waktu}} </h5>
                          </div>
                        </div>
                        <div class="cardKeterangan col">
                          <p class="card-text">Pertanyaan:</p>
                          <p class="card-text">{{j.pertanyaan.pertanyaan}}</p>
                          <p class="card-text">Jawaban:</p>
                          <p class="card-text">{{j.jawaban}}</p>
                        </div>
                        <div class="cardButton row">

                          <a href="{%url 'qna:question'%}">
                            <button id="button11" class="btn btn-primary intabel" method="POST">Kembali</button>
                          </a>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                  {%endfor%}
                {%endif%}
                
          </div>
        </div>
      </section>
    {%endblock content%}
</body>

</html>

qna/templates/qna/question.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'static/css/style.css' %}"> -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    {%block style%}
    <link rel="stylesheet" href="{% static 'qna/css/question.css' %}">
    <script type="text/javascript">
      $('#exampleModalCenter').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
    })
    </script>
    {%endblock style%}
    <title> Register </title>
</head>


<body>
    {%block content%}
    <section id="navbarMatkul">
      <div class="navMatkulCurhat col">
        <div class="navMatkul row">
          <a href="#">
            <h3 class="tulisanMatkul"> Matematika </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Fisika </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Kimia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Kimia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Biologi </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> IPS </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> PKN </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Indonesia </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> Inggris </h3>
          </a>
          <a href="#">
            <h3 class="tulisanMatkul"> IT </h3>
          </a>
        </div>
      </section>
      <section id="curhatAkademik">
        <div class="curhat row">
          <button class="btn btn-primary intabel" method="POST">Curhatan Siswa</button>
        </div>
      </section> 

      <section id="cardQuestion">
        <div class="container">
          <div class="col">
            {%if pertanyaan%}
              {%for p in pertanyaan%}
                  <div class="col-sm-6">
                    <div class="card">
                      <div class="card-body">
                        <div class="cardTitle row">
                          <img id="fotoakun2" src="{{p.usernanya.profile.image.url}}" class="rounded-circle">
                          <div class="tulisanjudul row">
                            <h5 id="cardtitle" class="card-title">{{p.usernanya.first_name}} {{p.usernanya.last_name}}</h5>
                            <h5 id="cardtitle" class="card-title"> {{p.matpel}} </h5>
                            <h5 id="cardtitle" class="card-title"> {{p.waktu}} </h5>
                          </div>
                        </div>
                        <div class="cardKeterangan col">
                          <p class="card-text">Pertanyaan:</p>
                          <p class="card-text">{{p.pertanyaan}}</p>
                        </div>
                        <div class="cardButton row">

                          <button type="button" id="button11" class="btn btn-primary intabel ask" id="ask-button" data-toggle="modal" data-target="#exampleModalCenter">
                            Jawab
                          </button>
                          
                          <!-- Modal -->
                          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h5 class="modal-title" id="exampleModalLongTitle">Jawab...</h5>
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                <form action="{%url 'qna:question'%}" method="POST">
                                  {%csrf_token%}
                                  <div class="modal-body">
                                    {{form}}
                                    <input type="hidden" value="{{ p.id }}" name="p_id"/>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="submit" method="POST" class="btn btn-primary">Save changes</button>
                                  </div>
                                </form>
                              </div>
                            </div>
                          </div>

                          <a href="{%url 'qna:hasil' p.id%}">
                            <button id="button11" class="btn btn-primary intabel" method="POST">Lihat Hasil</button>
                          </a>
                          
                        </div>
                      </div>
                    </div>
                  </div>
                {%endfor%}
              {%endif%}
          </div>
        </div>
      </section>
    {%endblock content%}
</body>

</html>