account/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profilesetting/', views.profilesetting, name='profilesetting'),
]

braincilonaction/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('dudupage.urls'), name="dudupage"),
    path('account/', include(('account.urls'), 'account'), name="account"),
    path('loginpage/', include(('loginpage.urls'), 'loginpage'), name="loginpage"),
    path('qna/', include(('qna.urls'), 'qna'), name="qna"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dudupage/urls.py
from django.urls import path

from .views import index

app_name = 'dudupage'

urlpatterns = [
    path('dudu/', index , name='index'),
]

loginpage/urls.py
from django.urls import path

from . import views

app_name = 'loginpage'

urlpatterns = [
    path('login/', views.loginView, name='loginView'),
    path('logout/', views.logout_user, name='logout_user'),
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
    path('question/', views.question, name='question'),
    path('hasil/<int:id_det>/', views.hasil, name='hasil'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block style %}
  {% endblock style %}
</head>

<body>
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light border-bottom shadow-sm">
    <a class="navbar-brand" href="#">
      <img id="logo" src="{% static 'img/Logo.png' %}">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">
      <ul class="navbar-nav">
        {%if user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'qna:question' %}">Question</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dudupage:index' %}">Dudu</a>
          </li>
          <li class="nav-item">            
            <a class="nav-link" href="{% url 'loginpage:logout_user' %}">Sign Out</a>
          </li>
          <li id="dropdown" class="nav-item">
              <div class="dropdown foto">
                <div id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="foto col">
                    <img id="fotoakun" src="{{user.profile.image.url}}" class="rounded-circle">
                  </div>
                </div>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <h6 class="dropdown-header">{{user.first_name}} {{user.last_name}}</h6>
                  <a class="dropdown-item" href="{% url 'account:profilesetting' %}">Profile Setting</a>
                </div>
              </div>
          </li>
        {%else%}
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginpage:loginView' %}">Question</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loginpage:loginView' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:register' %}">Register</a>
          </li>
        {%endif%}
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <footer id="contactus" >
    <div class="footercontent row">
      <div class="logobesar">
        <a href="#"> 
            <img id="logobesar" src="{% static 'img/LogoBesar.png' %}" alt="BraincilOnAction">
        </a> 
      </div>
      <div class="tulisan ">
        <h7>Contact Us</h7> <br/>
        <h7>087871833168</h7>
      </div>
    </div>
</footer>

</body>

</html>